fix: Move weasyprint check/err to after pip install

diff --git a/scripts/local-build b/scripts/local-build
--- a/scripts/local-build
+++ b/scripts/local-build
@@ -105,13 +105,6 @@ setup-venv(){
     printf "[INFO]: Setting up a local build for the ProLUG MkDocs course books...\n"
     printf "[INFO]: Attempting to set up virtual environment...\n"
 
-    # which weasyprint >/dev/null 2>&1 || {
-    #     printf >&2 "[ERROR]: The mkdocs-to-pdf plugin requires the 'weasyprint' package to build properly\n"
-    #     printf "[INFO]: Weasyprint has OS specific dependencies and cannot be easily installed via pip\n"
-    #     printf "[INFO]: Weasyprint documentation: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation\n"
-    #     exit 1
-    # }
-
     if ! [[ -d ./venv ]]; then
         python3 -m venv venv || {
             printf >&2 "[ERROR]: Failed to set up Python virtual environment.\n\n"
@@ -135,6 +128,15 @@ setup-venv(){
         return 1
     }
     printf "[INFO]: Virtual environment setup complete.\n"
+
+    type weasyprint > /dev/null 2>&1 || {
+        printf >&2 "[ERROR]: The 'weasyprint' package failed to install via pip\n"
+        printf >&2 "[ERROR]: The mkdocs-to-pdf plugin requires the 'weasyprint' package to build properly\n"
+        printf "[INFO]: Weasyprint has OS specific dependencies and cannot be easily installed via pip\n"
+        printf "[INFO]: Weasyprint documentation: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation\n"
+        return 1
+    }
+
     return 0
 }
 
@@ -153,14 +155,14 @@ serve-mkdocs(){
 }
 
 if [[ $REMOVE_VENV -eq 0 ]]; then
-	setup-venv || {
-	    printf >&2 "[ERROR]: Failed to set up python virtual environment!\n"
-	    exit 1
-	}
-	serve-mkdocs || {
-		printf >&2 "[ERROR]: Ran into a problem when building/serving mkdocs site.\n"
-		exit 1
-	}
+    setup-venv || {
+        printf >&2 "[ERROR]: Failed to set up python virtual environment!\n"
+        exit 1
+    }
+    serve-mkdocs || {
+        printf >&2 "[ERROR]: Ran into a problem when building/serving mkdocs site.\n"
+        exit 1
+    }
 fi
 
 exit 0
